sudo: required
language: python
services:
  - docker
python:
  - "2.7"
  - "3.5"
cache: pip
before_install:
  - docker-compose -f tests/server_dir/docker-compose.yml up -d
install: pip install tox-travis
jobs:
  include:
    - stage: test
      script: tox
    - stage: coverage
      python: 3.5
      script: codecov
