sudo: required
language: python
services:
  - docker
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script: true
jobs:
  include:
    - stage: flake8
      install: pip install flake8
      script: flake8 --ignore=E501,E402,F401 src tests
