sudo: required
language: python
jobs:
  include:
    - stage: flake8
      python:
        - "2.7"
        - "3.4"
        - "3.5"
        - "3.6"
      install: pip install flake8
      script: flake8 --ignore=E501,E402,F401 src tests
