sudo: required
language: python
services:
  - docker
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - docker-compose -f tests/server_dir/docker-compose.yml up -d
install:
  - pip install coverage 
  - pip install mock
  - pip install netaddr
  - pip install flake8
  - python setup.py install
script:
  - coverage run --append -m unittest discover -s tests/
stages:
 - name: flake8
 - test
 - name: deploy to pypi
jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - stage: flake8
      install: pip install flake8
      script: flake8 --ignore=E501,E402,F401 src tests
